version: "3.8"


services:
python_app:
build: .
container_name: python_app
ports:
- "5000:5000"


nginx:
image: nginx:latest
container_name: nginx_proxy
ports:
- "80:80"
volumes:
- ./nginx.conf:/etc/nginx/nginx.conf:ro
depends_on:
- python_app
